<a href="https://colab.research.google.com/github/EitanXotlanihua/Modelos-de-Regresi-n-Lineal/blob/main/Actividad_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [ ]:
df= pd.read_csv("cuentas_credicel.csv", encoding= 'latin')
pd.options.display.max_columns = None
df.head(2)

In [ ]:
df.info()

** *texto en cursiva*Convertir columna plazo**

In [26]:
#Eliminar un signo de una columna
df['plazo']=df['plazo'].str.replace('S', '')

In [27]:
#Conversión de tipo de dato de columna de tipo Object a int
df['plazo']= df['plazo'].astype(int)

In [ ]:
#Compruebo que la columna plazo ya se halla convertido a tipo numérico
df.info()

** *texto en cursiva*Convertir riesgo**

In [75]:
#Sustituyo los strings mic0437, mic0758 y mic09 por la constante "0"
df['dis_ventao']=df['dis_venta'].str.replace('mic0437', '0')
df['dis_ventao']=df['dis_venta'].str.replace('mic0758', '0')
df['dis_ventao']=df['dis_venta'].str.replace('mic09', '0')

In [30]:
riesgo_categorias = df.groupby(['dis_ventao'])['dis_ventao'].count()
riesgo_categorias

dis_ventao
0         288
00         99
001        22
005       135
006        82
         ... 
yvs043      4
yvs048      3
yvs049      1
yvs050      5
yvs054     14
Name: dis_ventao, Length: 585, dtype: int64

In [32]:
df["dis_ventao"]= df["dis_ventao"].fillna(0)

In [ ]:
#Compruebo que la columna riesgo ya se halla convertido a tipo numérico
df.info()

In [34]:
df["puntos"]=df["puntos"].fillna(method="bfill")

In [35]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['semana']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.01746764]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 138.18719129020198}

1er Modelo Matemático: y=0.01746764x + 138.18719129020198

In [41]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([ 671.05775453,  729.25859704,  678.4483377 , ...,  994.3957685 ,
       1591.18536001, 1073.84453765])

In [42]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.12651828911196095

In [43]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.3556940948511248

In [44]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.0710633]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 521.3984452016502}

**2do Modelo Matemático: y= 0.0710633x + 521.3984452016502**

In [46]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([ 671.05775453,  729.25859704,  678.4483377 , ...,  994.3957685 ,
       1591.18536001, 1073.84453765])

In [47]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.12651828911196095

In [48]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.3556940948511248

In [49]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['precio']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.49782094]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 1159.6103776221248}

**3er Modelo Matemático: y=0.49782094x + 1159.6103776221248**

In [50]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([2208.02128568, 2615.73663882, 2259.79466386, ..., 4473.10658087,
       8653.80686857, 5029.67039626])

In [51]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.7610877215641616

In [52]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.872403416754062

In [54]:
  #Declaramos las variables dependientes e independientes para la regresión lineal
  Vars_Indep= df[['costo_total']]
  Var_Dep= df['descuento']
  #Se define model como la función de regresión lineal
  from sklearn.linear_model import LinearRegression
  model= LinearRegression()
  #Ajustamos el modelo con las variables antes declaradas
  model.fit(X=Vars_Indep, y=Var_Dep)
  #Verificamos los coeficientes obtenidos para el modelo ajustado
  model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.00206296]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 66.71750919686258}

**4to Modelo Matemático: y=-0.03282908x +10.172388024218485**

In [55]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([71.06210139, 72.75166503, 71.27664916, ..., 80.44856602,
       97.77329787, 82.75495447])

In [56]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0013645781541555824

In [57]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.036940196996707836

In [59]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['monto_financiado']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.42741682]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 639.9922581004103}

**5to Modelo Matemático: y=0.42741682x + 639.9922581004103**

In [60]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([1540.1320761 , 1890.18644977, 1584.58342514, ..., 3484.87859647,
       7074.32503122, 3962.73059862])

In [61]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.8646380417764322

In [62]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.929859151579653

In [63]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['status']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-3.70544176e-05]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 1.4665759510725238}

**6to Modelo Matemático: y=-3.70544176e-05x + 1.4665759510725238**

In [64]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([1.38853935, 1.35819178, 1.38468569, ..., 1.21994175, 0.90875875,
       1.17851491])

In [65]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.038270065054901714

In [66]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.19562736274586362

In [67]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['fraude']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([6.70258031e-06]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 0.03661591611649644}

**7mo Modelo Matemático: y=6.70258031e-06x + 0.03661591611649644**

In [68]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

array([0.05073155, 0.05622096, 0.05142862, ..., 0.08122829, 0.13751656,
       0.08872178])

In [69]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0036945107407460043

In [70]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.06078248712208151

In [71]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['costo_total']]
Var_Dep= df['pagos_realizados']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['costo_total'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.00053865]),
 'rank_': 1,
 'singular_': array([359751.03527969]),
 'intercept_': 7.110616951868075}

**8vo Modelo Matemático: y=0.00053865x + 7.110616951868075**

In [ ]:
y_pred= model.predict(X=df[["costo_total"]])
y_pred

In [73]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.01752459482404467

In [74]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.13238049261142923